/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author llanos
 */
public class seleccionmesa extends javax.swing.JFrame {

    /**
     * Creates new form seleccionmesa
     */
    public seleccionmesa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Carta1 = new javax.swing.JLabel();
        Carta2 = new javax.swing.JLabel();
        Carta3 = new javax.swing.JLabel();
        Carta4 = new javax.swing.JLabel();
        Carta5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Mesa = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cartas 65 90/as corazones.png"))); // NOI18N
        getContentPane().add(Carta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        Carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cartas 65 90/cinco corazones.png"))); // NOI18N
        getContentPane().add(Carta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        Carta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cartas 65 90/q trebol.png"))); // NOI18N
        getContentPane().add(Carta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        Carta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cartas 65 90/tres diamantes.png"))); // NOI18N
        getContentPane().add(Carta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        Carta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cartas 65 90/ocho espadas.png"))); // NOI18N
        getContentPane().add(Carta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cartas 65 90/atras carta 65 92.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        Mesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesa poker 01.png"))); // NOI18N
        getContentPane().add(Mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/greenwallpapers.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seleccionmesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seleccionmesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seleccionmesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seleccionmesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seleccionmesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carta1;
    private javax.swing.JLabel Carta2;
    private javax.swing.JLabel Carta3;
    private javax.swing.JLabel Carta4;
    private javax.swing.JLabel Carta5;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Mesa;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
